name: CI Workflow

on: 
  push:
    branches:
      - main
  release:
    types: [created]  # Trigger on release creation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    # Grant execute permission for the gradlew file
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # Use ref_name for valid tag
        name: Release ${{ github.ref_name }}  # Use ref_name for valid tag
        draft: false
        prerelease: false
        files: app/build/outputs/apk/release/*.apk  # Adjust path as necessary
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use the secret here
