name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]  # Trigger on release creation

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Grant execute permission for the gradlew file
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # Configure Gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # Build the project
    - name: Build with Gradle Wrapper
      run: ./gradlew assembleRelease  # Use assembleRelease to build the release APK

    # Upload the APK to the release
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}  # Use the Git reference as the tag name
        release_name: Release ${{ github.ref }}  # Name of the release
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use the secret here

    - name: Upload APK
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        files: app/build/outputs/apk/release/*.apk  # Adjust the path if necessary
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use the secret here
